### ISSUE TITLE
Add Null Safety

### ISSUE THREAD

**Issue by Y0ngg4n** [KanarekApp/flutter_map_fast_markers#4]
Please add Null Safety to this

**Comment by TheLastGimbus** [comment]
I think @Xezolpl fixed this on `canary` branch in https://github.com/KanarekApp/flutter_map_fast_markers/commit/e0a1ed00b4d9f2bf2a7c67ea88efdf30afa1bde0 - don't know if it's okay to merge to dev (@Xezolpl submit it to review if it is pls), but definetley oaky to use since we do lol :+1: 

PS: By the way, nice to see that hour work got some attention! I'm not sure whether this approach is good yet, and how to fix "marker tapped" stuff (main flutter_map team is kinda not-responding) - but let us know if you have any feedback or actually using this :+1:

**Comment by Y0ngg4n** [comment]
@TheLastGimbus does marker tapping not work?

**Comment by TheLastGimbus** [comment]
It works but you need our fork of flutter_map on `canary` branch - its in the `pubspec.yaml` of this repo too

**Comment by Y0ngg4n** [comment]
@TheLastGimbus does the cluster plugin work with that?

**Comment by TheLastGimbus** [comment]
Nope, clustering is different thing - i might figure it out some day for `fast_markers`, but you can't use it yet 😕

**Comment by Y0ngg4n** [comment]
@TheLastGimbus would be nice if we could make https://github.com/Y0ngg4n/flutter_map_line_editor.git working :thinking:

**Comment by TheLastGimbus** [comment]
This library is for *very* specific use-case - if you want some more magic, you probably want to impmement your own - it's not that hard after all, you can inspire a lot from this library 👍👍

**Comment by Y0ngg4n** [comment]
hm ok thank you :)
