### ISSUE TITLE
Any plans to update this ?

### ISSUE THREAD

**Issue by jesussmile** [KanarekApp/flutter_map_fast_markers#6]
HI, couldn't get it to work with the current version of `flutter_map` any plans for future or is there a way i can still get it to work ? i guess you are not interested in this plugin anymore ? :(

**Comment by TheLastGimbus** [comment]
I'm gonna be honest with you - plans, yes, but not soon

I do want to update this, but it may take a half or whole year before i do - other priorities etc

Tho it works very simple - you can try to code this yourself. New flutter_map is easier to write plugins

**Comment by jesussmile** [comment]
okay. great. i got you. i have never made a plugin before but would want to give it a try. Unfortunately i never got to try your plugin and the code is broken. Could you please explain the logic behind it? as i understand- 
1. convert the marker into images and display them on canvas. 
2. will the ontap feature work ?
3. how to you populate the plugin all at once or only the ones that are visible ?
4. any other optimization tips ?

**Comment by TheLastGimbus** [comment]
No no no

There's no converting to image, that would be slower than widgets

What i did is use the Flutter's Canvas. Instead of giving your markers a widget, you give a functuon that draws the marker:

```dart
Marker(
  place: LatLng(51, 20),
  onDraw: (canvas, topLeft, bottomRight) {
    canvas.drawLine(...);
    // ... etc ...
  }
);
```

That's what makes this **"fast"**

And the simpler your canvas drawing gets, the faster it will be

For example our first marker design was a colorful dot with "glowing" shade with same color around - but I realized non-gradient shape:

```dart
canvas.drawCircle(red, radius: 2);
canvas.drawCircle(transparentRed, radius: 4);
// Instead of .drawShade()
```

Was much faster, so we went with that

And the library takes care of drawing them when necessary - yes, i think it was drawing only when visible

**Comment by jesussmile** [comment]
Ok. I spend the whole day trying to create a plugin. I guess my knowledge is limited.  One last question though,  do I really need to create a plugin?  Can't I just write classes based on ur logic?

**Comment by TheLastGimbus** [comment]
Plugins, classes... - i don't know what format `flutter_map` wants nowadays - try anything :+1:
